/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#ifndef __CPARSER_TREE_H__
#define __CPARSER_TREE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

extern cparser_node_t cparser_root;

cparser_result_t cparser_cmd_ssr_Number(cparser_context_t *context,
    uint32_t *Number_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw1(cparser_context_t *context,
    uint32_t *Number_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw1_console_ip_ipv4(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *ipv4_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw1_console_ip_ipv4_ipos_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *ipv4_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw1_console_ip_ipv4_shell_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *ipv4_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw1_console_ip_ipv4_ofw_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *ipv4_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw2(cparser_context_t *context,
    uint32_t *Number_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw2_console_ip_ipv4(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *ipv4_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw2_console_ip_ipv4_ipos_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *ipv4_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw2_console_ip_ipv4_shell_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *ipv4_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_rpsw2_console_ip_ipv4_ofw_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *ipv4_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc1(cparser_context_t *context,
    uint32_t *Number_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc1_slot_slot_number(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc1_slot_slot_number_shell_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc1_slot_slot_number_efi_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc2_a(cparser_context_t *context,
    uint32_t *Number_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc2_a_slot_slot_number(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc2_a_slot_slot_number_shell_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc2_a_slot_slot_number_efi_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc1_v2(cparser_context_t *context,
    uint32_t *Number_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc1_v2_slot_slot_number(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc1_v2_slot_slot_number_shell_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_ssr_Number_ssc1_v2_slot_slot_number_efi_field_Repeat_repeat_value_Expect_Enter_Expect_input(cparser_context_t *context,
    uint32_t *Number_ptr,
    uint32_t *slot_number_ptr,
    char **field_ptr,
    uint32_t *repeat_value_ptr,
    char **Enter_Expect_input_ptr);
cparser_result_t cparser_cmd_enable_privileged_mode(cparser_context_t *context);
cparser_result_t cparser_cmd_disable_privileged_mode(cparser_context_t *context);
cparser_result_t cparser_cmd_quit(cparser_context_t *context);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __CPARSER_TREE_H__ */
